### ISSUE TITLE
More options of open state.

### ISSUE THREAD

**Issue by JamesBliss** [SaloCreative/react-accordion#3]
I want to make is so that you can have all accordions closed. Currently one accordion is required to be open however, I would like to make it so all are closed by default and you can open one and then close that same one.

**Comment by JamesBliss** [comment]
Additionally, can you make it so you have the option to have multiple open?

**Comment by SaloCreative** [comment]
@JamesBliss can you give me a list of options you want and expected behaviour?

**Comment by JamesBliss** [comment]
- I want it so I can have many open at the same time. Ego, when I click on another toggle it doesn't close my already open accordion 
- I want to make it so all accordions can be closed. E.g. If the first open is open I can close it.

- I want to be able to set a value that ensures all accordions start closed.

- I want an exposed function to toggle all accordions closed.

**Comment by JamesBliss** [comment]
Might be better to break this into multiple issues?

**Comment by SaloCreative** [comment]
@JamesBliss ok so I propose the following properties for the first 3 points:

1. `multipleOpen: PropTypes.bool` default is `false` - toggles whether we have one or multiple items open at once
2. `activeClickClose: PropTypes.bool` default is `false` - toggles functionality of whether a click on an open accordion closes it or we enforce at least one item being open
3. `firstOpen: PropTypes.bool` default is `false` - toggles whether we start with the first item open

**Comment by JamesBliss** [comment]
@SaloCreative Looks good 👍
